name = "thoselashes-admin"
compatibility_date = "2024-09-01"
main = "functions/_worker.js"

[assets]
directory = "./build"

[vars]
ENV = "development"

[[kv_namespaces]]
binding = "APPOINTMENTS_KV"
id = "APPOINTMENTS_KV"
